Update some scripts, add/remove config files

diff --git a/.local/bin/ucopy b/.local/bin/ucopy
--- a/.local/bin/ucopy
+++ b/.local/bin/ucopy
@@ -2,17 +2,20 @@
 
 # Copy unicode characters from a file
 
-[ -z "$1" ] && echo "Incorrect usage!" && exit
-file="$HOME/.local/share/chars/$1"
+dir=$HOME/.local/share/chars
 
-! [ -f $file ] && exit
+case $1 in
+    -h|--help)  echo "Usage: ucopy [character_type]"
+esac
+
+[ -n "$1" ] && file=$dir/$1 || file=$dir/$(ls "$dir" | dmenu -i)
+[ -f "$file" ] || exit
 
 # Chose a character
 char=$(cut -d ';' -f1 "$file" | dmenu -p "Select:" -i -l 30 | sed "s/ .*//")
 [ -z "$char" ] && exit
 
 # Type char and copy to clipboard
-echo -n $char | xclip 
+echo -n $char | xclip || notify-send -i ~/.icons/notification/warn.png "xclip not found!"
 xdotool click --window $(xdotool getactivewindow) 2
 echo -n $char | xclip -sel c
-notify-send -i ~/.icons/notification/clipboard.png "'$char' in clipboard." 
